### ISSUE TITLE
Saifa: Write name meaning

### ISSUE THREAD

**Issue by matt-auckland** [matt-auckland/uoa-karate-wiki#51]

**Comment by Matteas-Eden** [comment]
This appears to be a duplicate of #50.

**Comment by matt-auckland** [comment]
The wonders of late night issue creation. There were a few other issues I made that were actually already complete 🤦‍♂️

I closed #50

**Comment by matt-auckland** [comment]
Turns out that this is also a duplicate of #3 lol. Closing this
